on: workflow_dispatch

name: Rebuild hep-arxiv dataset

jobs:
  update:
    name: Rebuild hep-arxiv dataset
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: r-lib/actions/setup-r@v1
      - name: Install R package dependencies
        run: |
          install.packages("aRxiv")
          install.packages("dplyr")
          install.packages("magrittr")
          install.packages("lubridate")
          install.packages("kgrams")
          install.packages("reticulate")
        shell: Rscript {0}
      - name: Install Python dependencies
        run: |
          Rscript -e "reticulate::install_miniconda()"
          echo "options(reticulate.conda_binary = reticulate:::miniconda_conda())" >> .Rprofile
          Rscript -e "reticulate::conda_create('r-reticulate', packages = c('python==3.8', 'numpy', 'pylatexenc'))"
      - name: Rebuild hep_arxiv
        env:
          KAGGLE_API_AUTH: ${{ secrets.KAGGLE_API_AUTH }}
        run: Rscript data-raw/hep_kaggle.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'rebuild hep_arxiv.rds' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
